export const storeMap = new Map()
export const expirationMap = new Map()
export const subscriberMap = new Map()
export const channelMap = new Map()
export const transactionMap = new Map()
export const watchMap = new Map()
